#!/usr/bin/env bash
# Script that transfers a file from the client to server.

#Check no. of parameters passed.
if [ $# -lt 3 ]; then
   echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
# With or without the ssh key the transfer of files will take place
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
