#!/usr/bin/env bash
#installing nginx on your web-01 server and should be
# listening at port 80.
# Update package list and install Nginx

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Nginx is installed and configured."
