#!/usr/bin/env bash
# Adding a custom Nginx response heade
# to be able to track which web server is answering our HTTP requests


sudo apt-get -y update
sudo apt-get -y install nginx

echo "Ceci n'est pas une page" |
    sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

nginx_config_path="/etc/nginx/sites-available/default"
nginx_config_content=$(cat <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
}
EOF
)

echo "$nginx_config_content" | sudo tee "$nginx_config_path" > /dev/null

sudo systemctl restart nginx
