#!/usr/bin/env bash
# Adding a custom Nginx response heade
# to be able to track which web server is answering our HTTP requests


sudo apt-get update

apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    add_header X-Served-By \$hostname;
}" > /etc/nginx/sites-available/custom_header

ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

nginx -t

service nginx start
