#!/usr/bin/env bash
# Adding a custom Nginx response heade
# to be able to track which web server is answering our HTTP requests

import subprocess

subprocess.call(["sudo", "apt-get", "-y", "update"])

subprocess.call(["sudo", "apt-get", "-y", "install", "nginx"])

with open("/usr/share/nginx/html/custom_404.html", "w") as custom_404_file:
    custom_404_file.write("Ceci n'est pas une page")

nginx_config_path = "/etc/nginx/sites-available/default"
nginx_config_content = """
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Served-By $hostname;
    }
}
"""

with open(nginx_config_path, "w") as nginx_config_file:
    nginx_config_file.write(nginx_config_content)

subprocess.call(["sudo", "systemctl", "restart", "nginx"])
