#!/usr/bin/env bash
# Script hat displays listening TCP ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
lsof -iTCP -sTCP:LISTEN -n -P

echo
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         PID/Program name"
lsof -iUDP -sUDP:LISTEN -n -P

echo
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
lsof -U | grep 'LISTEN'
