#!/usr/bin/env bash
# Script hat displays listening TCP ports
ss -tlnp | awk 'NR > 1 {
    split($4, addr, ":")
    split($6, parts, ",")
    split(parts[1], program, "=")
    printf "%s\t%s\t%s\n", addr[1], addr[2], program[2]
}'
