#!/usr/bin/env bash
#bash acript that stops the infinity and beyond process.

./4-to_infinity_and_beyond &
pid=$!
sleep 1

if ps -p $pid > /dev/null; then
    echo "Terminating process $pid"
    kill -SIGTERM $pid
else
    echo "Process $pid not found"
fi
