#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=":" read -r username _ gid _ home shell; do
	read -r _ _ _ _ info < <(grep "^${username}:" /etc/passwd)
	password="${info##*:}"
	echo "The user ${username} is part of the ${gid} gang, lives in ${home} and rides ${shell}. ${gid}'s place is protected by the passcode ${password}, more info about the user here: ${info}"
done < /etc/passwd	
