#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes.

hour=0
minutes=1

while [[ $hour -lt 12 ]]; do
  echo "Hour: $hour"
  while [[ $minutes -le 59 ]]; do
    echo "$minutes"
    ((minutes++))
  done
  ((hour++))
  minutes=0
done
